# Generated by Django 5.0.2 on 2024-03-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='video',
        ),
    ]
