# Generated by Django 4.2 on 2024-03-21 12:03

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
